# Generated by Django 4.0.3 on 2022-04-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='time_stamp')),
                ('title', models.TextField(verbose_name='title')),
                ('rule', models.TextField(verbose_name='rule')),
                ('p_content', models.TextField(verbose_name='captured_packets')),
                ('source', models.TextField(verbose_name='source_ip')),
                ('dest', models.TextField(verbose_name='destination_ip')),
                ('s_port', models.TextField(verbose_name='source_port')),
                ('d_port', models.TextField(verbose_name='destination_port')),
                ('protocol', models.TextField(verbose_name='protocol')),
            ],
        ),
        migrations.CreateModel(
            name='CapturedPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='time_stamp')),
                ('title', models.TextField(verbose_name='title')),
                ('rule', models.TextField(verbose_name='rule')),
                ('p_content', models.TextField(verbose_name='captured_packets')),
                ('source', models.TextField(verbose_name='source_ip')),
                ('dest', models.TextField(verbose_name='destination_ip')),
                ('s_port', models.TextField(verbose_name='source_port')),
                ('d_port', models.TextField(verbose_name='destination_port')),
                ('protocol', models.TextField(verbose_name='protocol')),
            ],
        ),
    ]
